# NumPy
- c언어로 구현됨
- 빠른 연산 속도
- 편리한 수치 연산 기능

In [1]:
import numpy as np

# Numpy 배열 특징
1. 그리드 형태
2. 값들이 동일하 데이터 타입
3. 양의 정수로 색인
4. 파이썬의 기본 리스트와 다르다.

In [38]:
myList123 = [[[1,2,3,4], [5,6,7,8],[9,10,11,12]],[[1,2,3,4], [5,6,7,8],[9,10,11,12]]]

In [39]:
myArray123 = np.array(myList123)

In [58]:
myArray123

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [40]:
myArray123[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
myArray123[1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
myArray123[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [45]:
myArray123[0][1]

array([5, 6, 7, 8])

In [48]:
myArray123[0][0][3]

4

In [49]:
myArray123[0][1][3]

8

In [50]:
myArray123[0][2][3]

12

In [47]:
myArray123[0][2]

array([ 9, 10, 11, 12])

In [44]:
myArray

array([1, 2, 3, 4, 5])

In [33]:
myArray[4]

5

In [29]:
myArray[1]

2

In [30]:
myArray[4]

5

In [34]:
myArray[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

In [6]:
print("차원: ", myArray.ndim)# 차원(축)의 개수

차원:  3


In [7]:
print("모양: ", myArray.shape)# 각 차원에서 배열의 모양

모양:  (2, 3, 4)


In [8]:
print("크기: ", myArray.size) # 배열의 크기

크기:  24


In [9]:
print("원소의 타입: ", myArray.dtype)# 원소의 타입을 나타냄.

원소의 타입:  int64


In [18]:
print("각 원소의 크기:  ", myArray.itemsize )#원소의 크기를 바이트 단위로 나타냄

각 원소의 크기:   8


In [19]:
myTestList = [[[1,2,3,4], ["test",6,7,8],[9,10,11,12]],[[1,2,3,4], [5,6,7,8],[9,10,11,12]]]

In [20]:
myTestArray = np.array(myTestList)
myTestArray

array([[['1', '2', '3', '4'],
        ['test', '6', '7', '8'],
        ['9', '10', '11', '12']],

       [['1', '2', '3', '4'],
        ['5', '6', '7', '8'],
        ['9', '10', '11', '12']]], dtype='<U21')

In [21]:
myTestArray.dtype

dtype('<U21')

In [22]:
myTestArray.itemsize

84

In [23]:
import numpy as np
myList = [1,2,3,4,5]
myArray = np.array(myList)

In [24]:
myArray

array([1, 2, 3, 4, 5])

In [25]:
a = [1,2,3,4,5]

In [26]:
a

[1, 2, 3, 4, 5]

# 리스트와 numpy의 array와는 다르다.  

In [52]:
npArray = np.arange(0,15,3)
npArray

array([ 0,  3,  6,  9, 12])

In [53]:
my_list = [1,2,3,4,5]

In [54]:
my_array = np.array(my_list)

In [55]:
myArray2 = my_array

In [56]:
myArray2

array([1, 2, 3, 4, 5])

In [65]:
zeroArray = np.zeros((3,3), dtype = int) # int으로 안하면 float으로 저장이됨.

In [66]:
zeroArray

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
oneArray = np.ones((2,4), dtype = int)

In [68]:
oneArray

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [69]:
import numpy as np

In [70]:
fullArray = np.full((1,2,3), 8) #

In [71]:
fullArray

array([[[8, 8, 8],
        [8, 8, 8]]])

In [72]:
eyeArray = np.eye(4)

In [73]:
eyeArray # 단위 행렬

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
eyeArray = np.eye(4, dtype = int)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [75]:
dtype= float

In [76]:
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [77]:
dtype

float

In [78]:
dtype = "float"

In [79]:
dtype

'float'

In [80]:
dtype = skjdflkjs

NameError: name 'skjdflkjs' is not defined

In [81]:
myArray3 = np.array([1,2,3,4,5], dtype=np.float64)

In [82]:
myArray3

array([1., 2., 3., 4., 5.])

In [83]:
intArray = np.array([1,2,3], dtype=np.int32)
floatArray = np.array([1.0,2.0,3.0], dtype=np.float64)

In [84]:
print("intArray 원소의 크기 : ", intArray.itemsize)

intArray 원소의 크기 :  4


In [85]:
print("floatArray 원소의 크기 : ", floatArray.itemsize)

floatArray 원소의 크기 :  8


In [88]:
a = 2
b = 23
print("a = {1}", a)

a = {1} 2


In [89]:
for i in range(5):
    print(f"Number {i}")


Number 0
Number 1
Number 2
Number 3
Number 4


In [91]:
name = "리눅스"
age = 23
print(f"Name: {name}, Age: {age}")


Name: 리눅스, Age: 23


# indexing, slicing

In [95]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Original array: \n", arr)
print("Element at position (1,1): ", arr[1,1])
arr[0,0]  =10

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at position (1,1):  5


In [96]:
arr

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [97]:
arr = np.array([1,2,3,4,5])

In [98]:
print("Original array: ", arr)

Original array:  [1 2 3 4 5]


# boolean indexing

In [100]:
print("Elements greater than 2: ", arr[arr>2])

Elements greater than 2:  [3 4 5]


In [104]:
Arr = np.array([1,2,3,4,5])

In [105]:
print("Original array : ", arr)

Original array :  [1 2 3 4 5]


In [106]:
sliceArr = Arr[1:4]

In [107]:
sliceArr[0]


2

# Numpy -  수학연산처리(기본 연산, 브로드캐스팅, 행렬연산)

In [108]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [109]:
print(np.add(a,b))

[5 7 9]


In [110]:
print(np.subtract(a,b))

[-3 -3 -3]


In [111]:
print(np.multiply(a,b))

[ 4 10 18]


In [112]:
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [113]:
print(np.divide(a,b))

[0.25 0.4  0.5 ]


In [114]:
print("a % b = ", a%b)

a % b =  [1 2 3]


In [115]:
print("a % b = ", np.mod(a,b))

a % b =  [1 2 3]


In [116]:
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [117]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [118]:
a = np.array([1,2,3])

In [119]:
b=2

In [120]:
print(a*b)

[2 4 6]


In [121]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [122]:
b = np.array([1,2,3])
result = a+b

In [123]:
print(result)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [124]:
c = np.array([[1],[2],[3]])
d = np.array([1,2,3])

# 행렬의 곱셈

In [125]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[6,5], [4,3], [2,1]])
print(A*B)

[[ 6 10]
 [12 12]
 [10  6]]


In [126]:
print(np.transpose(A))

[[1 3 5]
 [2 4 6]]


In [127]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [128]:
print(A.T)

[[1 3 5]
 [2 4 6]]


In [130]:
E = np.array([[1,2], [3,4]])

In [131]:
print(np.linalg.inv(E))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [132]:
print(np.linalg.det(E))

-2.0000000000000004


In [133]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
CrossProduct = np.cross(v1,v2)

In [134]:
print(CrossProduct)

[-3  6 -3]


# Numpy 집계 함수

In [135]:
data = np.array([[1,2,3],[4,5,6]])

In [136]:
total = np.sum(data, axis=None)

In [141]:
print(total)

[5 7 9]


In [140]:
# 각 열의 합계를 계산
total = np.sum(data, axis=0)
print(total)

[5 7 9]


In [139]:
# 각 행의 합계를 계산
total = np.sum(data, axis=1)
print(total)

[ 6 15]


In [142]:
min = np.min(data)

In [143]:
min

1

In [144]:
max = np.max(data)

In [145]:
max

6

In [146]:
avg = np.mean(data)

In [147]:
avg

3.5

In [148]:
median = np.median(data)

In [149]:
median

3.5

In [150]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
data2 = np.array([1,2,3,4,5,6])
middle = np.median(data)

In [152]:
print(middle)

3.5


In [153]:
data = np.array([1,2,3,4,5])

In [154]:
std_dev = np.std(data)

In [155]:
print(std_dev)

1.4142135623730951


In [156]:
data = np.array([1,2,3,4,5])

In [157]:
var = np.var(data)

In [158]:
var

2.0

In [159]:
# 원본은 그대로 유지한다.
np.sort(data)

array([1, 2, 3, 4, 5])

In [160]:
# 원본을 변경하고 싶다면 배열의 sort 함수를 사용하기
data.sort()

In [161]:
data = np.array([5,1,6,2,3])
partition_data = np.partition(data,3)

In [162]:
print("Original : ", data)

Original :  [5 1 6 2 3]


In [163]:
print("Partition data : ", partition_data)

Partition data :  [2 3 1 5 6]


In [164]:
data = np.array([1,2,3,4,5,6])

In [165]:
split_data = np.array_split(data,3)
print(data)
print(split_data)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [166]:
data = np.array([5,1,6,2,3])

In [167]:
sort_indic = np.argsort(data)

In [169]:
# 정렬했을때 인덱스를 반환
data = np.array([5,1,6,2,3])
print(sort_indic)

[1 3 4 0 2]


In [171]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi])

In [172]:
print("sin: ", np.sin(angles))

sin:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [173]:
print("Cos : ", np.cos(angles))

Cos :  [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [174]:
print("tan: ", np.tan(angles))

tan:  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [175]:
value = np.array([1,2,3])
print("exp: ", np.exp(value))

exp:  [ 2.71828183  7.3890561  20.08553692]


In [176]:
value

array([1, 2, 3])

In [178]:
values = np.array([1, np.e, np.e**2])
print("log: ", np.log(values))
print("log: ", np.log2(values))
print("log: ", np.log10(values))

log:  [0. 1. 2.]
log:  [0.         1.44269504 2.88539008]
log:  [0.         0.43429448 0.86858896]


In [179]:
values = np.array([1,4,9])

In [180]:
print("sqrt:", np.sqrt(values))

sqrt: [1. 2. 3.]


In [181]:
arr = np.array([True, False, True])

In [182]:
print(np.any(arr))

True


In [183]:
print(np.all(arr))

False


In [184]:
arr = np.array([1,2,3,4,5])

In [185]:
index = np.where(arr>3)

In [187]:
index
print(arr[index])

[4 5]


In [190]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])

print("AND: ", np.logical_and(arr1,arr2))
print("OR: ", np.logical_or(arr1,arr2))
print("NOT: ", np.logical_not(arr1))

AND:  [False False  True]
OR:  [ True False  True]
NOT:  [False  True False]
